[package]
name = "pgsqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
# Async runtime
tokio = { version = "1.45", features = ["full"] }
tokio-util = { version = "0.7.15", features = ["codec"] }

# PostgreSQL protocol
bytes = "1.9"
postgres-protocol = "0.6.8"

# SQLite
rusqlite = { version = "0.36", features = ["bundled", "uuid", "serde_json", "functions", "collation"] }

# SQL parsing
sqlparser = "0.57"

# Types
uuid = { version = "1.11", features = ["v4", "serde"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
chrono = "0.4.39"
rust_decimal = { version = "1.35", features = ["serde", "db-postgres"] }

# PostgreSQL client (for testing)
tokio-postgres = { version = "0.7.12", features = ["with-chrono-0_4"] }
env_logger = "0.11"

# Utilities
thiserror = "2.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
once_cell = "1.19"
async-trait = "0.1"
rand = "0.9"
futures = "0.3"
hex = "0.4"
regex = "1.11"
byteorder = "1.5"

# Configuration
config = "0.15"
clap = { version = "4.5", features = ["derive"] }

# Metrics
prometheus = "0.14"

[dev-dependencies]
criterion = "0.6"
pretty_assertions = "1.4"
