name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 'stable'
    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        # Cache key differentiation
        key: "v1-rust"
        # Clean cache if it gets too large
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
    - name: Free disk space
      run: |
        # Free up disk space before building
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        df -h
    - name: Build and test
      run: |
        # Set minimal profile for faster compilation and less disk usage
        export CARGO_PROFILE_DEV_DEBUG=0
        export CARGO_PROFILE_TEST_DEBUG=0
        # Build and test in one step to avoid duplicate compilation
        cargo test --release --verbose
      env:
        # Reduce parallel jobs to save memory and disk space
        CARGO_BUILD_JOBS: 2
    - name: Install bc (for test timing calculations)
      run: sudo apt-get install -y bc
    - name: Run integration tests - TCP with SSL
      run: |
        chmod +x tests/runner/run_ssl_tests.sh
        ./tests/runner/run_ssl_tests.sh --mode tcp-ssl
    - name: Run integration tests - TCP without SSL
      run: ./tests/runner/run_ssl_tests.sh --mode tcp-no-ssl
    - name: Run integration tests - Unix socket
      run: ./tests/runner/run_ssl_tests.sh --mode unix-socket
    - name: Run integration tests - File DB with SSL
      run: ./tests/runner/run_ssl_tests.sh --mode file-ssl
    - name: Run integration tests - File DB without SSL
      run: ./tests/runner/run_ssl_tests.sh --mode file-no-ssl
